<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="$(SolutionDir)\3rdparty\fmt\libfmt.props" />
    
  <ItemDefinitionGroup>
    <ClCompile>
      <PreprocessorDefinitions>NOMINMAX;_HAS_EXCEPTIONS=0;_ITERATOR_DEBUG_LEVEL=0;%(PreprocessorDefinitions)</PreprocessorDefinitions>
      <AdditionalIncludeDirectories>$(SolutionDir);%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>
      <ExceptionHandling>false</ExceptionHandling>
      <RuntimeTypeInfo>false</RuntimeTypeInfo>
      <LanguageStandard>stdcpplatest</LanguageStandard>
      <LanguageStandard_C>stdc17</LanguageStandard_C>
      <DisableSpecificWarnings>26429;26446;26481;26485;26821;26812;%(DisableSpecificWarnings)</DisableSpecificWarnings>
      <AdditionalOptions>/Zc:char8_t %(AdditionalOptions)</AdditionalOptions>
    </ClCompile>
    <Link>
      <StackReserveSize>8388608</StackReserveSize>
      <StackCommitSize>32768</StackCommitSize>
    </Link>
    <Manifest>
      <EnableDpiAwareness>true</EnableDpiAwareness>
    </Manifest>
  </ItemDefinitionGroup>
  <ItemGroup />
</Project>